/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll;

import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.krysalis.barcode4j.impl.code128.Code128Bean;
import org.krysalis.barcode4j.output.bitmap.BitmapCanvasProvider;

/**
 *
 * @author Midoriya Izuku
 */
public class Employees extends javax.swing.JFrame {

    /**
     * Creates new form Employees
     */
    
    sqlConnection getDB = new sqlConnection();
    Connection conn = getDB.DbconnectP();
    
    
    public Employees() {
        initComponents();
        showEmployee();
    }
    
   public void createImage(String myString)  {
		try {
		Code128Bean code128 = new Code128Bean();
		code128.setHeight(15f);
		code128.setModuleWidth(0.5);
		code128.setQuietZone(10);
		code128.doQuietZone(true);
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		BitmapCanvasProvider canvas = new BitmapCanvasProvider(baos, "image/x-png", 100, BufferedImage.TYPE_BYTE_BINARY, false, 0);
		code128.generateBarcode(canvas, myString);
		canvas.finish();
		//write to png file
		FileOutputStream fos = new FileOutputStream("src\\Barcodes\\"+ myString + ".png");
		fos.write(baos.toByteArray());
		fos.flush();
		fos.close();
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
    
    public void showEmployee(){
        try {
            sqlConnection getDB = new sqlConnection();
            Connection conn = getDB.DbconnectP();
            
            DefaultTableModel model = (DefaultTableModel)jtblEmp.getModel();
            Object[] empTable = new Object[9];
            String getAllEmp = "SELECT * FROM `employees` LEFT JOIN positions ON positions.ID=employees.POSITION_ID where employees.ID>1";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(getAllEmp);
            
            while(rs.next()){
                String fullname = rs.getString("FIRST_NAME") + " " + rs.getString("MIDDLE_NAME") + " " + rs.getString("LAST_NAME");
                empTable[0] = rs.getInt("ID");
                empTable[1] = rs.getString("EMP_BARCODE");
                empTable[2] = fullname;
                empTable[3] = rs.getString("ADDRESS");
                empTable[4] = rs.getString("DOB");
                empTable[5] = rs.getString("POS_DESCRIPTION");
                empTable[6] = rs.getInt("RATE_PRICE");
                empTable[7] = rs.getDouble("DAYS_OF_WORK");
                model.addRow(empTable);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEmp = new javax.swing.JTable();
        jbtnAdd = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtn_x = new javax.swing.JButton();
        empcode = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jdtDoB = new com.toedter.calendar.JDateChooser();
        jcmbPos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtxtDoW = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtFname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtMname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtLname = new javax.swing.JTextField();
        jlblAddress = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(248, 211, 162));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 106, 78));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/administrator-64.png"))); // NOI18N
        jLabel1.setText("EMPLOYEES");
        jLabel1.setToolTipText("");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 1000, 80));

        jtblEmp.setBackground(new java.awt.Color(204, 102, 0));
        jtblEmp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BARCODE", "FULL NAME", "ADDRESS", "DATA OF BIRTH", "POSITION", "RATE", "DAYS OF WORK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblEmp);
        if (jtblEmp.getColumnModel().getColumnCount() > 0) {
            jtblEmp.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtblEmp.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtblEmp.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtblEmp.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtblEmp.getColumnModel().getColumn(4).setResizable(false);
            jtblEmp.getColumnModel().getColumn(4).setPreferredWidth(30);
            jtblEmp.getColumnModel().getColumn(5).setPreferredWidth(10);
            jtblEmp.getColumnModel().getColumn(6).setResizable(false);
            jtblEmp.getColumnModel().getColumn(6).setPreferredWidth(30);
            jtblEmp.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1240, 420));

        jbtnAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-emp.png"))); // NOI18N
        jbtnAdd.setText("    ADD");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 170, 40));

        jbtnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit-emp.png"))); // NOI18N
        jbtnUpdate.setText("   UPDATE");
        jPanel3.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 580, 170, 40));

        jbtnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove-emp.png"))); // NOI18N
        jbtnDelete.setText("  DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 650, 170, 40));

        jbtn_x.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_x.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_x.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_x.setText("X");
        jbtn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_xActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, -1, -1));
        jPanel3.add(empcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 710, 310, 80));

        jPanel1.setBackground(new java.awt.Color(248, 211, 162));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("DATE OF BIRTH");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));
        jPanel1.add(jdtDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 160, -1));

        jcmbPos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcmbPos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(jcmbPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 160, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("POSITION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 80, 10));

        jtxtDoW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDoWActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtDoW, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 160, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("DAYS OF WORK");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("BARCODE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("FIRST NAME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jtxtFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtFnameFocusLost(evt);
            }
        });
        jtxtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("MIDDLE NAME");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jtxtMname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtMname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("LAST NAME");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jtxtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, 30));

        jlblAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblAddress.setText("ADDRESS");
        jPanel1.add(jlblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jtxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 160, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 1200, 250));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private String generateCode(String data){
        String code=data;
        Random objGenerator = new Random();
        for (int iCount = 0; iCount< 10; iCount++){
          int randomNumber = objGenerator.nextInt(10);
          code+=randomNumber;
         }
        return code;
    }
    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try {
            addNewEmployee();
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jtxtMnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMnameActionPerformed

    private void jtxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAddressActionPerformed

    private void jtxtDoWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDoWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDoWActionPerformed

    private void jtxtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFnameActionPerformed

    int idselected;
    
    private void jtblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEmpMouseClicked
        idselected = Integer.parseInt(jtblEmp.getValueAt(jtblEmp.getSelectedRow(),0).toString());
    }//GEN-LAST:event_jtblEmpMouseClicked

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        try {
            deleteEmployee(idselected);
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jtxtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLnameActionPerformed

    private void jbtn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_xActionPerformed
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_jbtn_xActionPerformed

    private void jtxtFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtFnameFocusLost
       String codes = generateCode(jtxtFname.getText());
       createImage(codes);
       String filePath = "src\\Barcodes\\"+ codes + ".png";
       ImageIcon vin = new ImageIcon(filePath);
       empcode.setIcon(vin);
    }//GEN-LAST:event_jtxtFnameFocusLost

    public void addNewEmployee() throws SQLException{
        DateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");  
        String strDate = dateFormat.format(jdtDoB.getDate());
        
        String addEmployee = "INSERT INTO `employees`(`EMP_BARCODE`,`FIRST_NAME`, `MIDDLE_NAME`, `LAST_NAME`,`ADDRESS`,`DOB`, `POSITION_ID`, `DAYS_OF_WORK`) VALUES (?,?,?,?,?,?,?,?)";
        PreparedStatement st = conn.prepareStatement(addEmployee);
            st.setString(1, generateCode(jtxtFname.getText()));
            st.setString(2, jtxtFname.getText());
            st.setString(3, jtxtMname.getText());
            st.setString(4, jtxtLname.getText());
            st.setString(5, jtxtAddress.getText());
            st.setString(6, strDate);
            st.setInt(7, 2);
            st.setInt(8, Integer.parseInt(jtxtDoW.getText()));
            int i = st.executeUpdate();
           if (i > 0) {
                JOptionPane.showMessageDialog(this,"Successfully Added");
                DefaultTableModel mod = (DefaultTableModel)jtblEmp.getModel();
                mod.setRowCount(0);
                 showEmployee();
          } else {
                JOptionPane.showMessageDialog(this,"Error");
            }
    }
    
     public void updateEmployee() throws SQLException{
        String updateEmployee = "UPDATE `employees` SET `FIRST_NAME`=?, `MIDDLE_NAME`=?, `LAST_NAME`=?, `DOB`=?, `POSITION_ID`=?, `DAYS_OF_WORK`=? WHERE ID = ?";
        PreparedStatement st = conn.prepareStatement(updateEmployee);
//        st.setString(1, .getText());
//        st.setString(2, .getText());
//        st.setString(3, .getText());
//        st.setString(4, .getText());
//        st.setInt(5, .getText());
//        st.setInt(6, .getText());
//        st.setInt(6, .getText());

            int i = st.executeUpdate();
            if (i > 0) {
                  JOptionPane.showMessageDialog(this,"Successfully Updated");
                  showEmployee();
            } else {
                JOptionPane.showMessageDialog(this,"Error");
            }
    }
     
     public void deleteEmployee(int id) throws SQLException{
        String deleteEmployee = "DELETE FROM employees WHERE ID = ?";
        PreparedStatement st = conn.prepareStatement(deleteEmployee);
        st.setInt(1,id);

            int i = st.executeUpdate();
            if (i > 0) {
                  JOptionPane.showMessageDialog(this,"Successfully Updated");
                  DefaultTableModel mod = (DefaultTableModel)jtblEmp.getModel();
                mod.setRowCount(0);
                 showEmployee();
            } else {
                JOptionPane.showMessageDialog(this,"Error");
            }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel empcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JButton jbtn_x;
    private javax.swing.JComboBox<String> jcmbPos;
    private com.toedter.calendar.JDateChooser jdtDoB;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JTable jtblEmp;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtDoW;
    private javax.swing.JTextField jtxtFname;
    private javax.swing.JTextField jtxtLname;
    private javax.swing.JTextField jtxtMname;
    // End of variables declaration//GEN-END:variables
}
