/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class Payrolls extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Payrolls() {
        initComponents();
        jtxtsearchEmpToPayOut.requestFocusInWindow();
        jpnl_payslip.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_empPayroll = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jbtn_x = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jtxtsearchEmpToPayOut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpnl_payslip = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbl_fullname = new javax.swing.JLabel();
        jlbl_positions = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlbl_totalSalary = new javax.swing.JLabel();
        jlbl_DOW = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 210, 160));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PAYROLLS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 21, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 1262, 10));

        jtbl_empPayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMP_BARCODE", "FULLNAME", "DAYS OF WORK", "SALARY"
            }
        ));
        jScrollPane1.setViewportView(jtbl_empPayroll);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 153, 1215, 596));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printer-4-24.png"))); // NOI18N
        jButton1.setText("PRINT");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 755, 128, 48));

        jbtn_x.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_x.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jbtn_x.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_x.setText("X");
        jbtn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_xActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(1219, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtsearchEmpToPayOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtsearchEmpToPayOutKeyPressed(evt);
            }
        });
        jPanel3.add(jtxtsearchEmpToPayOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-3-24.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 340, 40));

        jpnl_payslip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("FULLNAME");
        jpnl_payslip.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 60, 29));

        jLabel3.setText("POSITION");
        jpnl_payslip.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 60, 29));

        jLabel5.setText("DAYS OF WORK");
        jpnl_payslip.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 137, 90, 29));

        jLabel6.setText("TOTAL SALARY");
        jpnl_payslip.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 80, 29));
        jpnl_payslip.add(jlbl_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 67, 260, 29));
        jpnl_payslip.add(jlbl_positions, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 102, 252, 29));
        jpnl_payslip.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 112, 260, 29));
        jpnl_payslip.add(jlbl_totalSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, 29));
        jpnl_payslip.add(jlbl_DOW, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, 29));

        jPanel1.add(jpnl_payslip, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 350, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_xActionPerformed
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_jbtn_xActionPerformed

    private void jtxtsearchEmpToPayOutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchEmpToPayOutKeyPressed
        if (evt.getKeyCode()==10) {
            new PaySlip(jtxtsearchEmpToPayOut.getText());
            JOptionPane.showMessageDialog(this,new PaySlip(jtxtsearchEmpToPayOut.getText()),"PaySlip",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jtxtsearchEmpToPayOutKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payrolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payrolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payrolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payrolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payrolls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtn_x;
    private javax.swing.JLabel jlbl_DOW;
    private javax.swing.JLabel jlbl_fullname;
    private javax.swing.JLabel jlbl_positions;
    private javax.swing.JLabel jlbl_totalSalary;
    private javax.swing.JPanel jpnl_payslip;
    private javax.swing.JTable jtbl_empPayroll;
    private javax.swing.JTextField jtxtsearchEmpToPayOut;
    // End of variables declaration//GEN-END:variables
}
