/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 63926
 */
public class PaySlip extends javax.swing.JPanel {

    /**
     * Creates new form PaySlip
     */
    String empcode;
    public PaySlip(String empcode) {
        initComponents();
        this.empcode=empcode;
        searchEmployee();
    }
    
    public void searchEmployee(){
       try {
            sqlConnection getDB = new sqlConnection();
            Connection conn = getDB.DbconnectP();
            
            String getAllEmp = "SELECT * FROM `employees` LEFT JOIN positions ON positions.ID=employees.POSITION_ID where employees.EMP_BARCODE='"+empcode+"'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(getAllEmp);
            
            while(rs.next()){
                String fullname = rs.getString("FIRST_NAME") + " " + rs.getString("MIDDLE_NAME") + " " + rs.getString("LAST_NAME");
                double totalsalary = rs.getInt("RATE_PRICE") * rs.getDouble("DAYS_OF_WORK");
                jlbl_fullname.setText(fullname);
                jlbl_positions.setText(rs.getString("POS_DESCRIPTION"));
                jlbl_DOW.setText(String.valueOf(rs.getDouble("DAYS_OF_WORK")));
                jlbl_totalSalary.setText(String.valueOf(totalsalary));
//                JOptionPane.showMessageDialog(this,"fullname : " +fullname + "\n" + "Rate : " + rs.getInt("RATE_PRICE") + "\n" + "Days Of Work : " + rs.getDouble("DAYS_OF_WORK") + "\n" + "SALARY : " + totalsalary);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbl_fullname = new javax.swing.JLabel();
        jlbl_positions = new javax.swing.JLabel();
        jlbl_totalSalary = new javax.swing.JLabel();
        jlbl_DOW = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("FULLNAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 100, 29));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("POSITION");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 100, 29));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("DAYS OF WORK");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 137, 130, 29));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("TOTAL SALARY");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 120, 29));
        add(jlbl_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 67, 250, 29));
        add(jlbl_positions, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 102, 240, 29));
        add(jlbl_totalSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 29));
        add(jlbl_DOW, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, 29));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlbl_DOW;
    private javax.swing.JLabel jlbl_fullname;
    private javax.swing.JLabel jlbl_positions;
    private javax.swing.JLabel jlbl_totalSalary;
    // End of variables declaration//GEN-END:variables
}
